### ISSUE TITLE
Find a proper name

### ISSUE THREAD

**Issue by s3rgiosan** [log-oscon/wp-genesis-boilerplate#25]
Find a proper name for your WordPress boilerplate. A name that could be marketed and recognized.
And independent of development environments and theme frameworks, I guess.

Avoid words like:
- Boilerplate
- VVV
- Starter
- Bootstrap
- Foundation
- Genesis

Current options and votes:

name | 👍  | 👎 
--- | --- | ---
WP Construct | 5 | 0
WP BootBox | 2 | 0
Step One | 1 | 0
WP Inception | 0 | 0
WP Base | 0 | 0
WPartida | 0 | 1

**Note:** Vote o the respective comments where the names were suggested.
**PS:** WP Seed is already taken by another starter.

**Comment by xipasduarte** [comment]
WP Seed

**Comment by xipasduarte** [comment]
Seed Boiler

**Comment by xipasduarte** [comment]
Step One

**Comment by xipasduarte** [comment]
WP Inception

**Comment by xipasduarte** [comment]
WPartida

**Comment by csrui** [comment]
vvv-boilerplate

**Comment by csrui** [comment]
wp-base

**Comment by csrui** [comment]
vvv-base

**Comment by s3rgiosan** [comment]
Description updated

**Comment by csrui** [comment]
Algum contexto então para poder fazer mais sugestões

**Comment by xipasduarte** [comment]
@csrui GitHub -> English 😄 . Delete your non conforming suggestions 😛

**Comment by xipasduarte** [comment]
We are in search of a name, so add your suggestion and vote for the ones that exist already. By the end of next week this will be closed with the "winner".

I've updated the description to reflect the suggestions, look for their entries along the discussion to vote.

**Comment by Narayon** [comment]
WP Seed is already taken by another starter.  
I'm removing that from the options and I'm gone clean up others that don't fit the name criteria.

**Comment by liciniofs** [comment]
WP BootBox

**Comment by Narayon** [comment]
WP Construct  

Since we use OOP, I think we can play with some of the reserved words of the paradigm.  
I'm not sure about the _WP_, but I understand the marketing advantages.

**Comment by zecalabs** [comment]
WP Construct

**Comment by tiago-jacob** [comment]
WP Construct

**Comment by csrui** [comment]
WP Construct
