### ISSUE TITLE
Add proper placeholders

### ISSUE THREAD

**Issue by s3rgiosan** [log-oscon/wp-genesis-boilerplate#33]
Add proper placeholders across all files for immediate search and replace.

Or, better yet, convert this to a yeoman generator.

**Comment by Narayon** [comment]
I guess we should try to upgrade this repo to VVV 2 and use the `.yml` config.  
This issue is closed but is not forgotten. 🙂

**Comment by RicCastelhano** [comment]
A yeoman generator would be the better option, as it may do some sort of validation prior to generating the entire structure.

**Comment by Narayon** [comment]
I think a `.yml` with some defaults is enough.  
Do you have any use case where validation is useful (or even possible)?

**Comment by RicCastelhano** [comment]
@Narayon automation is always better then human "search&replace" for placeholders. Through a generator, a developer must input just the necessary data, and the Yeoman will scaffold the entire thing by itself.
