### ISSUE TITLE
Missing NPM on provisioning

### ISSUE THREAD

**Issue by csrui** [log-oscon/wp-genesis-boilerplate#43]
vvv-init.sh fails when requesting to npm install gulp as there is no NPM. Where does NPM install come from?

https://github.com/log-oscon/wp-genesis-boilerplate/blob/master/vvv-init.sh#L30

**Comment by RicCastelhano** [comment]
Isnt it supposed to be prior installed ?

**Comment by s3rgiosan** [comment]
@csrui look at some of the previous commits in `master`. I fixed it already.

**Comment by csrui** [comment]
So sorry @s3rgiosan cant find it... Mind pointing it out?
