### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by xipasduarte** [log-oscon/wp-genesis-boilerplate#8]
There a "missing" file when the `WP_DEBUG` option is set to `true`.
When this setting is present the file `wp-settings.php` forces the inclusion on a file named `advanced-cache.php` in the `wp-content` directory.

```
// For an advanced caching plugin to use. Uses a static drop-in because you would only wa
nt one.
if ( WP_CACHE )
        WP_DEBUG ? include( WP_CONTENT_DIR . '/advanced-cache.php' ) : @include( WP_CONTE
NT_DIR . '/advanced-cache.php' );
```

**Comment by goblindegook** [comment]
Not really a bug. We could add an empty `advanced-cache.php` file, but managed hosts provide their own so we have to be careful.

Perhaps add `touch wp-content/advanced-cache.php` to the VVV provisioning script so it only takes effect in development?

**Comment by xipasduarte** [comment]
You're right, not really a bug.

I agree with having the VVV scripts creating the file. It could also serve as a way to provide its content without having an extra file to filter when deploying.

I'll do this as soon as I can. Thanks for the feedback.
